site_name: Discope PMS
site_url: https://discope.run/
docs_dir: docs
# dev_addr: 127.0.0.1:8000
repo_name: discope
repo_url: https://github.com/discope-pms/discope
edit_uri: ""
theme:
  name: material
  # favicon: '_assets/img/favicon.png'
  # logo: '_assets/img/logo.png'
  feature:
    tabs: true
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  # 404 page
  static_templates:
    - 404.html
extra_css:
  - '_assets/css/extra.css'
plugins:
  - search
  - mike:
      canonical_version: null
      version_selector: true
      css_dir: css
extra:
  version:
    provider: mike
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - 'Home': 'index.md'
  - 'Concepts': 'concepts.md'
  - 'Installation':
      - 'Vue d’ensemble': 'setup/index.md'
      - 'Sécurité': 'setup/securite.md'
      - 'Organisation': 'setup/organisation.md'
      - 'Compta': 'setup/compta.md'
      - 'Communication': 'setup/communication.md'
      - 'Paramètres': 'setup/parametres.md'
      - 'Ventes': 'setup/ventes.md'
      - 'Catalogue des produits': 'setup/catalogue_produits.md'
      - 'Prix': 'setup/prix.md'
      - 'Emails': 'setup/emails.md'
  - 'Descriptif applicatif':
      - 'Introduction': 'application-description/index.md'
      - 'Catalogue':
          - 'Catalogue': 'application-description/catalog.md'
          - 'Tarification': 'application-description/pricing.md'
          - 'Prix, réductions et gratuités': 'application-description/prices-discounts-freebies.md'
          - 'Tours-opérateurs et commissions': 'application-description/travel-agencies.md'
          - 'Agences de voyage en ligne': 'application-description/online-travel-agencies.md'
          - 'Packs': 'application-description/packs.md'
          - 'Saisons': 'application-description/seasons.md'
          - 'Produits automatiques': 'application-description/automatic-products.md'
      - 'Réservations':
          - 'Réservations': 'application-description/bookings.md'
          - 'Contrats': 'application-description/contracts.md'
          - 'Financements': 'application-description/fundings.md'
          - 'Plans de paiement': 'application-description/payment-plans.md'
          - 'Planning et récapitulatifs': 'application-description/planning-and-summaries.md'
      - 'Administration':
          - 'Entités Discope': 'application-description/discope-entities.md'
          - 'Caisse / point de vente': 'application-description/cashdesk-pos.md'
          - 'Rôles et utilisateurs': 'application-description/roles-and-users.md'
          - 'Modèles et e-mails': 'application-description/templates-and-emails.md'
          - 'Traductions': 'application-description/translations.md'
          - 'Comptabilité et facturation': 'application-description/accounting-and-billing.md'
          - 'Statistiques': 'application-description/statistics.md'
          - 'Support': 'application-description/support.md'
