site_name: Discope PMS
site_url: https://discope.run/
docs_dir: docs
# dev_addr: 127.0.0.1:8000
repo_name: discope
repo_url: https://github.com/discope-pms/discope
edit_uri: ""
theme:
  name: material
  # favicon: '_assets/img/favicon.png'
  # logo: '_assets/img/logo.png'
  feature:
    tabs: true
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  # 404 page
  static_templates:
    - 404.html
extra_css:
  - '_assets/css/extra.css'
plugins:
  - search
  - mike:
      canonical_version: null
      version_selector: true
      css_dir: css
extra:
  version:
    provider: mike
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - 'Accueil': 'index.md'
  - 'Concepts':
      - 'Vue d’ensemble': 'concepts/index.md'
      - 'Organisation': 'concepts/organization.md'
      - 'Centres': 'concepts/centers.md'
      - 'Unités locatives': 'concepts/rental_units.md'
  - 'Installation':
      - 'Vue d’ensemble': 'setup/index.md'
      - 'Sécurité': 'setup/security.md'
      - 'Organisation': 'setup/organization.md'
      - 'Compta': 'setup/accounting.md'
      - 'Communication': 'setup/communication.md'
      - 'Paramètres': 'setup/settings.md'
      - 'Ventes': 'setup/sales.md'
      - 'Catalogue des produits': 'setup/product_catalog.md'
      - 'Prix': 'setup/prices.md'
      - 'Emails': 'setup/emails.md'
  - 'Descriptif applicatif':
      - 'Introduction': 'logic/index.md'
      - 'Catalogue':
          - 'Catalogue': 'logic/catalog.md'
          - 'Tarification': 'logic/pricing.md'
          - 'Prix, réductions et gratuités': 'logic/prices-discounts-freebies.md'
          - 'Tours-opérateurs et commissions': 'logic/travel-agencies.md'
          - 'Agences de voyage en ligne': 'logic/online-travel-agencies.md'
          - 'Packs': 'logic/packs.md'
          - 'Saisons': 'logic/seasons.md'
          - 'Produits automatiques': 'logic/automatic-products.md'
      - 'Réservations':
          - 'Réservations': 'logic/bookings.md'
          - 'Contrats': 'logic/contracts.md'
          - 'Financements': 'logic/fundings.md'
          - 'Plans de paiement': 'logic/payment-plans.md'
          - 'Planning et récapitulatifs': 'logic/planning-and-summaries.md'
      - 'Administration':
          - 'Entités Discope': 'logic/discope-entities.md'
          - 'Caisse / point de vente': 'logic/cashdesk-pos.md'
          - 'Rôles et utilisateurs': 'logic/roles-and-users.md'
          - 'Modèles et e-mails': 'logic/templates-and-emails.md'
          - 'Traductions': 'logic/translations.md'
          - 'Comptabilité et facturation': 'logic/accounting-and-billing.md'
          - 'Statistiques': 'logic/statistics.md'
          - 'Support': 'logic/support.md'
